// LAW CORPUS — versioned, cited. Schema per docs/D11-corpus-spec.md
// HARD RULE: no entry without act + section + source. Amend via changelog, never overwrite silently.
// last_verified "PENDING-HUMAN" = figures from published reporting of the act, awaiting
// human check against bdlaws.minlaw.gov.bd before stage use. HALT item.

export const CORPUS_VERSION = "2026-07-18.1";

export type Verdict = "illegal" | "civil" | "cannot-verify";

export interface CorpusEntry {
  id: string;
  domain: "traffic" | "family" | "land";
  act_bn: string;
  act_en: string;
  section: string;
  offense_bn: string;
  offense_en: string;
  verdict: Verdict;
  penalty_bn: string;
  penalty_en: string;
  next_bn: string;
  next_en: string;
  keywords: string[]; // lowercase; multi-word keywords act as natural weighting
  source: string;
  effective_date: string;
  last_verified: string; // ISO date or "PENDING-HUMAN"
}

export const CORPUS: CorpusEntry[] = [
  // ---------- TRAFFIC — সড়ক পরিবহণ আইন, ২০১৮ ----------
  {
    id: "tr-helmet",
    domain: "traffic",
    act_bn: "সড়ক পরিবহণ আইন, ২০১৮",
    act_en: "Road Transport Act, 2018",
    section: "ধারা ৪৯(১)(চ) ও ৯২(১) / s.49(1)(f), s.92(1)",
    offense_bn: "হেলমেট ছাড়া মোটরসাইকেল চালানো বা আরোহণ করা",
    offense_en: "Riding a motorcycle without a helmet (rider or pillion)",
    verdict: "illegal",
    penalty_bn: "সর্বোচ্চ ৩ মাস কারাদণ্ড, অথবা সর্বোচ্চ ৳১০,০০০ জরিমানা, অথবা উভয়",
    penalty_en: "Up to 3 months imprisonment, or fine up to ৳10,000, or both",
    next_bn: "হেলমেট পরুন (চালক ও আরোহী উভয়ে)। মামলা হলে নির্ধারিত জরিমানা পরিশোধ করুন। আপত্তি থাকলে আইনজীবীর পরামর্শ নিন।",
    next_en: "Wear a helmet (both rider and pillion). If fined, pay the prescribed fine. Consult a lawyer if you wish to contest.",
    keywords: ["হেলমেট", "helmet"],
    source: "http://bdlaws.minlaw.gov.bd/act-1262.html",
    effective_date: "2019-11-01",
    last_verified: "2026-07-18",
  },
  {
    id: "tr-license",
    domain: "traffic",
    act_bn: "সড়ক পরিবহণ আইন, ২০১৮",
    act_en: "Road Transport Act, 2018",
    section: "ধারা ৪ ও ৬৬ / s.4, s.66",
    offense_bn: "বৈধ ড্রাইভিং লাইসেন্স ছাড়া মোটরযান চালানো",
    offense_en: "Driving a motor vehicle without a valid driving licence",
    verdict: "illegal",
    penalty_bn: "সর্বোচ্চ ৬ মাস কারাদণ্ড, অথবা সর্বোচ্চ ৳২৫,০০০ জরিমানা, অথবা উভয়",
    penalty_en: "Up to 6 months imprisonment, or fine up to ৳25,000, or both",
    next_bn: "বিআরটিএ থেকে লাইসেন্স করুন। লাইসেন্স ছাড়া গাড়ি চালাবেন না। মামলা হলে আইনজীবীর পরামর্শ নিন।",
    next_en: "Get a licence from BRTA. Do not drive without one. If charged, consult a lawyer.",
    keywords: ["লাইসেন্স", "ড্রাইভিং লাইসেন্স", "license", "licence", "driving"],
    source: "http://bdlaws.minlaw.gov.bd/act-1262.html",
    effective_date: "2019-11-01",
    last_verified: "PENDING-HUMAN",
  },
  {
    id: "tr-registration",
    domain: "traffic",
    act_bn: "সড়ক পরিবহণ আইন, ২০১৮",
    act_en: "Road Transport Act, 2018",
    section: "ধারা ৭২ / s.72",
    offense_bn: "রেজিস্ট্রেশন ছাড়া মোটরযান চালানো",
    offense_en: "Driving an unregistered motor vehicle",
    verdict: "illegal",
    penalty_bn: "সর্বোচ্চ ৬ মাস কারাদণ্ড, অথবা সর্বোচ্চ ৳৫০,০০০ জরিমানা, অথবা উভয়",
    penalty_en: "Up to 6 months imprisonment, or fine up to ৳50,000, or both",
    next_bn: "বিআরটিএ-তে গাড়ির রেজিস্ট্রেশন করুন। রেজিস্ট্রেশন ছাড়া গাড়ি রাস্তায় নামাবেন না।",
    next_en: "Register the vehicle with BRTA. Do not drive an unregistered vehicle.",
    keywords: ["রেজিস্ট্রেশন", "নিবন্ধন", "registration", "unregistered"],
    source: "http://bdlaws.minlaw.gov.bd/act-1262.html",
    effective_date: "2019-11-01",
    last_verified: "PENDING-HUMAN",
  },
  {
    id: "tr-fitness",
    domain: "traffic",
    act_bn: "সড়ক পরিবহণ আইন, ২০১৮",
    act_en: "Road Transport Act, 2018",
    section: "ধারা ৭৫ / s.75",
    offense_bn: "ফিটনেস সনদ ছাড়া মোটরযান চালানো",
    offense_en: "Driving a vehicle without a fitness certificate",
    verdict: "illegal",
    penalty_bn: "সর্বোচ্চ ৬ মাস কারাদণ্ড, অথবা সর্বোচ্চ ৳২৫,০০০ জরিমানা, অথবা উভয়",
    penalty_en: "Up to 6 months imprisonment, or fine up to ৳25,000, or both",
    next_bn: "বিআরটিএ থেকে ফিটনেস সনদ নবায়ন করুন। সনদ গাড়িতে রাখুন।",
    next_en: "Renew the fitness certificate at BRTA and keep it in the vehicle.",
    keywords: ["ফিটনেস", "fitness"],
    source: "http://bdlaws.minlaw.gov.bd/act-1262.html",
    effective_date: "2019-11-01",
    last_verified: "PENDING-HUMAN",
  },
  {
    id: "tr-reckless",
    domain: "traffic",
    act_bn: "সড়ক পরিবহণ আইন, ২০১৮",
    act_en: "Road Transport Act, 2018",
    section: "ধারা ১০৫ / s.105",
    offense_bn: "বেপরোয়া বা অবহেলায় গাড়ি চালিয়ে দুর্ঘটনায় মৃত্যু ঘটানো",
    offense_en: "Causing death by reckless or negligent driving",
    verdict: "illegal",
    penalty_bn: "সর্বোচ্চ ৫ বছর কারাদণ্ড, অথবা জরিমানা, অথবা উভয়",
    penalty_en: "Up to 5 years imprisonment, or fine, or both",
    next_bn: "দুর্ঘটনা ঘটলে আহতকে সাহায্য করুন, পুলিশে খবর দিন এবং দ্রুত একজন আইনজীবীর সাথে যোগাযোগ করুন।",
    next_en: "If an accident occurs, help the injured, inform police, and contact a lawyer immediately.",
    keywords: ["বেপরোয়া", "দুর্ঘটনা", "reckless", "accident", "গতি", "overspeed"],
    source: "http://bdlaws.minlaw.gov.bd/act-1262.html",
    effective_date: "2019-11-01",
    last_verified: "PENDING-HUMAN",
  },

  // ---------- FAMILY — যৌতুক / বিবাহ / তালাক / দেনমোহর ----------
  {
    id: "fa-dowry-demand",
    domain: "family",
    act_bn: "যৌতুক নিরোধ আইন, ২০১৮",
    act_en: "Dowry Prohibition Act, 2018",
    section: "ধারা ৩ / s.3",
    offense_bn: "প্রত্যক্ষ বা পরোক্ষভাবে যৌতুক দাবি করা বা চাওয়া",
    offense_en: "Demanding dowry, directly or indirectly",
    verdict: "illegal",
    penalty_bn: "সর্বনিম্ন ১ বছর থেকে সর্বোচ্চ ৫ বছর কারাদণ্ড, অথবা সর্বোচ্চ ৳৫০,০০০ জরিমানা, অথবা উভয়",
    penalty_en: "Imprisonment of 1 to 5 years, or fine up to ৳50,000, or both",
    next_bn: "যৌতুক দাবির প্রমাণ (মেসেজ, সাক্ষী) সংরক্ষণ করুন। নিকটস্থ থানায় অভিযোগ করতে পারেন। একজন আইনজীবীর পরামর্শ নিন।",
    next_en: "Preserve evidence of the demand (messages, witnesses). You may file a complaint at the local police station. Consult a lawyer.",
    keywords: ["যৌতুক চাওয়া", "যৌতুক দাবি", "যৌতুক", "dowry demand", "dowry"],
    source: "http://bdlaws.minlaw.gov.bd (যৌতুক নিরোধ আইন, ২০১৮); legislativediv.portal.gov.bd official PDF",
    effective_date: "2018-11-18",
    last_verified: "2026-07-18",
  },
  {
    id: "fa-dowry-give",
    domain: "family",
    act_bn: "যৌতুক নিরোধ আইন, ২০১৮",
    act_en: "Dowry Prohibition Act, 2018",
    section: "ধারা ৪ / s.4",
    offense_bn: "যৌতুক দেওয়া, নেওয়া, বা দিতে-নিতে সহায়তা করা",
    offense_en: "Giving or taking dowry, or abetting it",
    verdict: "illegal",
    penalty_bn: "সর্বনিম্ন ১ বছর থেকে সর্বোচ্চ ৫ বছর কারাদণ্ড, অথবা সর্বোচ্চ ৳৫০,০০০ জরিমানা, অথবা উভয়",
    penalty_en: "Imprisonment of 1 to 5 years, or fine up to ৳50,000, or both",
    next_bn: "যৌতুক লেনদেনে জড়াবেন না — দাতা ও গ্রহীতা উভয়েই অপরাধী। প্রয়োজনে আইনজীবীর পরামর্শ নিন।",
    next_en: "Do not engage in dowry — both giver and taker commit an offence. Consult a lawyer if needed.",
    keywords: ["যৌতুক দেওয়া", "যৌতুক নেওয়া", "যৌতুক", "giving dowry", "taking dowry"],
    source: "http://bdlaws.minlaw.gov.bd (যৌতুক নিরোধ আইন, ২০১৮)",
    effective_date: "2018-11-18",
    last_verified: "PENDING-HUMAN",
  },
  {
    id: "fa-child-marriage",
    domain: "family",
    act_bn: "বাল্যবিবাহ নিরোধ আইন, ২০১৭",
    act_en: "Child Marriage Restraint Act, 2017",
    section: "ধারা ৭ / s.7",
    offense_bn: "প্রাপ্তবয়স্ক কর্তৃক অপ্রাপ্তবয়স্ককে (মেয়ে <১৮, ছেলে <২১) বিবাহ করা",
    offense_en: "An adult marrying a minor (girl under 18, boy under 21)",
    verdict: "illegal",
    penalty_bn: "সর্বোচ্চ ২ বছর কারাদণ্ড, অথবা সর্বোচ্চ ৳১,০০,০০০ জরিমানা, অথবা উভয়",
    penalty_en: "Up to 2 years imprisonment, or fine up to ৳100,000, or both",
    next_bn: "বাল্যবিবাহের খবর পেলে ১০৯ (জাতীয় হেল্পলাইন) বা স্থানীয় প্রশাসনকে জানান। আইনজীবীর সাহায্য নিন।",
    next_en: "Report child marriage to helpline 109 or local administration. Seek a lawyer's help.",
    keywords: ["বাল্যবিবাহ", "বাল্য বিবাহ", "নাবালিকা", "অপ্রাপ্তবয়স্ক", "child marriage", "minor"],
    source: "http://bdlaws.minlaw.gov.bd (বাল্যবিবাহ নিরোধ আইন, ২০১৭)",
    effective_date: "2017-03-11",
    last_verified: "PENDING-HUMAN",
  },
  {
    id: "fa-talaq-notice",
    domain: "family",
    act_bn: "মুসলিম পারিবারিক আইন অধ্যাদেশ, ১৯৬১",
    act_en: "Muslim Family Laws Ordinance, 1961",
    section: "ধারা ৭ / s.7",
    offense_bn: "চেয়ারম্যান/মেয়রকে লিখিত নোটিশ না দিয়ে তালাক দেওয়া",
    offense_en: "Pronouncing talaq without written notice to the chairman/mayor",
    verdict: "illegal",
    penalty_bn: "সর্বোচ্চ ১ বছর বিনাশ্রম কারাদণ্ড, অথবা অর্থদণ্ড, অথবা উভয় (অর্থদণ্ডের সঠিক অঙ্ক সংশোধনী অনুযায়ী — যাচাই সাপেক্ষ)",
    penalty_en: "Up to 1 year simple imprisonment, or fine, or both (exact fine amount per amendment — pending verification)",
    next_bn: "তালাকের নোটিশ অবশ্যই লিখিতভাবে স্থানীয় চেয়ারম্যান/মেয়র বরাবর দিন এবং স্ত্রীকে কপি দিন। ৯০ দিনের সালিশ প্রক্রিয়া প্রযোজ্য। আইনজীবীর পরামর্শ নিন।",
    next_en: "Talaq notice must be given in writing to the local chairman/mayor with a copy to the wife; a 90-day arbitration period applies. Consult a lawyer.",
    keywords: ["তালাক", "ডিভোর্স", "divorce", "talaq", "নোটিশ"],
    source: "http://bdlaws.minlaw.gov.bd (Muslim Family Laws Ordinance, 1961)",
    effective_date: "1961-07-15",
    last_verified: "PENDING-HUMAN",
  },
  {
    id: "fa-mahr",
    domain: "family",
    act_bn: "পারিবারিক আদালত আইন (দেনমোহর মামলা)",
    act_en: "Family Courts law (mahr/dower suits)",
    section: "পারিবারিক আদালতের এখতিয়ার / family court jurisdiction",
    offense_bn: "স্ত্রীর দেনমোহর পরিশোধ না করা",
    offense_en: "Not paying the wife's mahr (dower)",
    verdict: "civil",
    penalty_bn: "এটি সরাসরি ফৌজদারি অপরাধ নয় — তবে দেনমোহর স্ত্রীর আইনি পাওনা; পারিবারিক আদালতে মামলা করে ডিক্রিসহ আদায়যোগ্য",
    penalty_en: "Not directly a criminal offence — but mahr is a legal debt; recoverable by decree through the Family Court",
    next_bn: "কাবিননামার কপি সংগ্রহ করুন। পারিবারিক আদালতে দেনমোহর ও ভরণপোষণের মামলা করা যায়। একজন আইনজীবীর সাহায্য নিন।",
    next_en: "Collect a copy of the kabinnama (marriage contract). A suit for mahr and maintenance can be filed in the Family Court. Get a lawyer's help.",
    keywords: ["দেনমোহর", "মোহরানা", "mahr", "dower", "denmohor", "কাবিন"],
    source: "http://bdlaws.minlaw.gov.bd (পারিবারিক আদালত সংক্রান্ত আইন)",
    effective_date: "1985-06-15",
    last_verified: "PENDING-HUMAN",
  },

  // ---------- LAND — দণ্ডবিধি, ১৮৬০ ----------
  {
    id: "la-trespass",
    domain: "land",
    act_bn: "দণ্ডবিধি, ১৮৬০",
    act_en: "Penal Code, 1860",
    section: "ধারা ৪৪৭ / s.447",
    offense_bn: "অন্যের জমি বা সম্পত্তিতে অনধিকার প্রবেশ (ক্রিমিনাল ট্রেসপাস)",
    offense_en: "Criminal trespass on another's land or property",
    verdict: "illegal",
    penalty_bn: "সর্বোচ্চ ৩ মাস কারাদণ্ড, অথবা সর্বোচ্চ ৳৫০০ জরিমানা, অথবা উভয়",
    penalty_en: "Up to 3 months imprisonment, or fine up to ৳500, or both",
    next_bn: "জমির দলিল, খতিয়ান ও দখলের প্রমাণ গুছিয়ে রাখুন। থানায় অভিযোগ বা আদালতে মামলা করা যায়। আইনজীবীর পরামর্শ নিন।",
    next_en: "Organize your deed, khatian, and possession records. You may file a police complaint or a court case. Consult a lawyer.",
    keywords: ["জমি দখল", "দখল", "অনধিকার প্রবেশ", "trespass", "land grab", "জমিতে ঢুকে"],
    source: "http://bdlaws.minlaw.gov.bd/act-11.html (Penal Code, 1860)",
    effective_date: "1860-10-06",
    last_verified: "PENDING-HUMAN",
  },
  {
    id: "la-cheating",
    domain: "land",
    act_bn: "দণ্ডবিধি, ১৮৬০",
    act_en: "Penal Code, 1860",
    section: "ধারা ৪২০ / s.420",
    offense_bn: "জমি বিক্রি বা হস্তান্তরে প্রতারণা করা",
    offense_en: "Cheating in the sale or transfer of land",
    verdict: "illegal",
    penalty_bn: "সর্বোচ্চ ৭ বছর কারাদণ্ড এবং জরিমানা",
    penalty_en: "Up to 7 years imprisonment, plus fine",
    next_bn: "সব কাগজপত্র (বায়না, দলিল, রশিদ) সংরক্ষণ করুন। থানায় প্রতারণার মামলা করা যায়। দ্রুত আইনজীবীর পরামর্শ নিন।",
    next_en: "Preserve all papers (agreement, deed, receipts). A cheating case can be filed with police. Consult a lawyer quickly.",
    keywords: ["প্রতারণা", "ঠকিয়ে", "জমি বিক্রি", "cheating", "fraud", "বায়না"],
    source: "http://bdlaws.minlaw.gov.bd/act-11.html (Penal Code, 1860)",
    effective_date: "1860-10-06",
    last_verified: "PENDING-HUMAN",
  },
  {
    id: "la-forgery",
    domain: "land",
    act_bn: "দণ্ডবিধি, ১৮৬০",
    act_en: "Penal Code, 1860",
    section: "ধারা ৪৬৭ / s.467",
    offense_bn: "জাল দলিল তৈরি করা (মূল্যবান দলিলের জালিয়াতি)",
    offense_en: "Forging a deed (forgery of a valuable security)",
    verdict: "illegal",
    penalty_bn: "যাবজ্জীবন কারাদণ্ড, অথবা সর্বোচ্চ ১০ বছর কারাদণ্ড এবং জরিমানা",
    penalty_en: "Imprisonment for life, or up to 10 years imprisonment plus fine",
    next_bn: "সন্দেহজনক দলিল সাব-রেজিস্ট্রি অফিসে যাচাই করুন। জালিয়াতির প্রমাণ পেলে মামলা করা যায়। আইনজীবীর সাহায্য নিন।",
    next_en: "Verify a suspicious deed at the sub-registry office. If forged, a case can be filed. Get a lawyer's help.",
    keywords: ["জাল দলিল", "দলিল জাল", "জালিয়াতি", "forgery", "fake deed", "জাল"],
    source: "http://bdlaws.minlaw.gov.bd/act-11.html (Penal Code, 1860)",
    effective_date: "1860-10-06",
    last_verified: "PENDING-HUMAN",
  },
];
